SDK-1305: Add goimports check to Travis, run goimports

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -30,9 +30,17 @@ jobs:
             GO111MODULE=off;
             go get -t -d ./...;
           fi
+        - go get golang.org/x/tools/cmd/goimports
       script:
         - ./.travis.gofmt.sh
-        - go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code) # Check that go generate ./... produces a zero diff; clean up any changes afterwards.
+        - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./yotiprotoattr/*" -not -path "./yotiprotocom/*" -not -path "./yotiprotoshare/*")) <(printf "")
+        # Check that go generate ./... produces a zero diff; clean up any changes afterwards.
+        - if [ $TRAVIS_GO_VERSION == "1.9.7" ] ||
+          [ $TRAVIS_GO_VERSION == "1.10.x" ]; then
+            go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code) 
+          else
+            go generate -x ./... && go mod tidy && git diff --exit-code; code=$?; git checkout -- .; (exit $code) 
+          fi
         - go vet ./...
         - go test -v -race ./...
     - <<: *test
